name: ai_soil_tester
description: AI Soil Tester - Flutter Bluetooth SPP app for ESP32 soil device (Localized)
publish_to: "none"
version: 1.2.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
